/*
 * ThumbySNES — generate the GFX.ZERO colour-math lookup table as a C
 * const array. Run at CMake build time; produces gfx_zero_table.c
 * which is compiled into snes9x2002 as read-only flash data.
 *
 * The table maps each 16-bit RGB565 pixel p = (R<<11)|(G<<5)|B to
 * a value where each channel is zeroed unless its top bit is set,
 * otherwise the channel's top bit is cleared. Matches the loop in
 * vendor/snes9x2002/src/gfx.c:486-513 for the RGB565 build.
 *
 * Saves 128 KB of SRAM on device (moves the LUT from malloc heap
 * into flash .rodata).
 *
 * Usage:  gen_gfx_zero <output.c>
 */
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>

int main(int argc, char **argv)
{
    if (argc < 2) {
        fprintf(stderr, "usage: %s <output.c>\n", argv[0]);
        return 1;
    }
    FILE *f = fopen(argv[1], "w");
    if (!f) { perror(argv[1]); return 1; }

    fprintf(f,
        "/* Auto-generated by tools/gen_gfx_zero.c — do not edit. */\n"
        "#include <stdint.h>\n"
        "const uint16_t thumbysnes_gfx_zero[0x10000] = {\n");

    for (int p = 0; p < 0x10000; p++) {
        int r = (p >> 11) & 0x1F;
        int g = (p >>  5) & 0x3F;
        int b = p & 0x1F;
        int r2 = (r & 0x10) ? (r & ~0x10) : 0;
        int g2 = (g & 0x20) ? (g & ~0x20) : 0;   /* GREEN_HI_BIT = 0x20 for RGB565 */
        int b2 = (b & 0x10) ? (b & ~0x10) : 0;
        int pv = (r2 << 11) | (g2 << 5) | b2;
        fprintf(f, "0x%04x,", pv);
        if ((p & 0xF) == 0xF) fputc('\n', f);
    }

    fprintf(f, "};\n");
    fclose(f);
    return 0;
}
